### ISSUE TITLE
Using enourmous map size prevents friends from joinning

### ISSUE THREAD

**Issue by Valerate** [Gedemon/Civ6-YnAMP#1]
Hi.

When I change map size to enormous or any other size noone can join my game, the only work around is to change size down, have them join, and change it back. But, the problem with this is that when we save and try to load, we cant join since the map size is up.

**Comment by Valerate** [comment]
Do you think its an engine bug? Since it seems to happen with all mods that adds more sizes (I have tried 2 others mods too and the same issue persist) 

Or does it even happen with others? I have yet to see anyone else complain about it haha

**Comment by FlashXAron** [comment]
For sure a engine bug ... 
or
1.) the other person has changed any of the files 
2.) anyone is using a NONE ENGLISH VERSION with special characters in his name, in any filename or directory name WHICH is involved with Civ VI or the mod !
We have a friend, who is using a Russian Windows 10, even he changed everything to English, it didn't help, as still there are some directory names, which are using Cyrillic chars

**Comment by Valerate** [comment]
I made sure to change both our files equally, and their user name is (neinar) and mine is (kas) so there shouldnt be an issue, and checking the files structure, no files have anything out of the default chars (C/users/<User>/documents/my games/civ/mods ). 
I assume it is a engine bug then, which sucks :< 
I love  having big empires and loads of cities :) 
I am using Norwegain windows, but I never use our letters (æøå) anywhere since I know it causes issues

**Comment by FlashXAron** [comment]
... maybe your friend, who I think has also a norwegian OS ... it is even enough, when any DLL is installed somewhere with special chars (DX , VC++) 
also heard that some people could fix such problems to build a new user in windows, with not more than 8 chars and of course without special chars ! 

I fear you will have to wait until Firaxis will fix it , as there was such bug also in Civ IV , when I remember correct ... as my friend with his russian OS , also couldn't join, we are also waiting (but 3 of us could join and play any mod, even in MP etc. and we have german OS, where also special chars are possible like äüöß ...)

**Comment by Gedemon** [comment]
Is this still happening since the fall patch ?
