### ISSUE TITLE
Bigger earth maps crashes during satellite launch

### ISSUE THREAD

**Issue by jbd00** [Gedemon/Civ6-YnAMP#105]
Hello,
I have one frequently occurring issue I want to address.
For some reason, on the big earth maps, whenever the satellite project is finished, the game always crashes or freezes during the natural wonder-revealings. I am experiencing this on my app-store version on my mac, but it does also appear others using this mod on steam are experiencing the same:
https://steamcommunity.com/app/289070/discussions/3/1796278072838327873/
https://steamcommunity.com/app/289070/discussions/3/1796278072836998936/
No clue if there even is a work-around. I have tried many different things, like changing to low-graphics, changing to strategic view, changing to windowed mode, freeing up RAM right before the sequence, but all leaves me with the same outcome.
Hope it is fixable :D
If of value, my specs are:
MBP 15" 2017
Running 10.14.5 beta (18F108f)
3,1 GHz Intel Core i7
16 GB 2133 MHz
Radeon Pro 560 4 GB

**Comment by Gedemon** [comment]
The game is now unstable with maps larger than Enormous, stick to that size until Firaxis restore the game's stability.

Nothing I can do on the mod's side.
