### ISSUE TITLE
Greatest Earth Map not appearing solved! 

### ISSUE THREAD

**Issue by ghengiseanie** [Gedemon/Civ6-YnAMP#107]
I updated my game to the antarctic  april update, and lost ability to see the YNAMP maps apart from the TSL Remastered.. I get an "unknown mod error" even with the latest update of YNAMP. I then rolled back to the update before gathering storm. Still cant see the map! 

I run this with Quo Mod. (not on spheres yet)
AI +13
TErra Mirabilis (new Update version just came out.)
CQUI (not update for april)
Would love to run with MOAR unique units, Real BUilding ugprades etc.. But the above is the minimum i owuld like to get the map going with, and tbh, due to Laptop its the greatest Earth map i ideally want ot see working..  (Indonesia needs much work!)
thank you and thanks so much for the amazin work put into it..

**Comment by Gedemon** [comment]
Can you test with the latest commit pushed today ?

And is your game updated to 1.0.0.317 ? older version, including 1.0.0.314, are surely incompatible.

**Comment by ghengiseanie** [comment]
I did go to 317. I then rolled back and to an older YNAMP, (diff drive same mod folder. yes complicated but needed my fi) with the map still not appearing. I wil check on my 317 install and report back with new commit

**Comment by ghengiseanie** [comment]
ok tried it, deleted all mods bar this commit. I get an unknown od appearing as per screenshot on Imgur https://imgur.com/a/ZR1ySeF

**Comment by Gedemon** [comment]
I'll need your log with latest commit please
see
https://steamcommunity.com/workshop/filedetails/discussion/1259095065/1621726179577842276/
or
https://forums.civfanatics.com/threads/how-to-get-the-log-files-before-reporting-a-bug.619054/

**Comment by ghengiseanie** [comment]
[Lua.log](https://github.com/Gedemon/Civ6-YnAMP/files/3112880/Lua.log)
[Modding.log](https://github.com/Gedemon/Civ6-YnAMP/files/3112881/Modding.log)
[Database.log](https://github.com/Gedemon/Civ6-YnAMP/files/3112882/Database.log)

hope this is what you need

**Comment by Gedemon** [comment]
Thanks for the logs.

Could you try to verify the installation files on steam ?

The error in Database.log is very strange and occurs before the mod is loaded.

You could also try to delete the Mods.sqlite file from the documents/my games/civilization VI folder

**Comment by ghengiseanie** [comment]
Excellent verifiying the game files worked! thanks
