### ISSUE TITLE
Glitched main menu and create game screen

### ISSUE THREAD

**Issue by Lakitu1** [Gedemon/Civ6-YnAMP#124]
![image](https://user-images.githubusercontent.com/13228258/73610434-eadd7300-45b5-11ea-835c-3986f43c02f0.png)
The main menu
![image](https://user-images.githubusercontent.com/13228258/73610438-f3ce4480-45b5-11ea-91a2-02413edb9ac0.png)
The create game screen

This only happens with YNAMP, even if it is disabled.

**Comment by Gedemon** [comment]
Update your game
