### ISSUE TITLE
[Bug] Not possible to start game if seeds are empty

### ISSUE THREAD

**Issue by 1e00** [Gedemon/Civ6-YnAMP#131]
Hi,
I cannot start the game if seeds on create game panel are empty (please check screen)
(This is currently working on steam version of YnAMP)

Version: latest from github:8.0.0 alpha 5.1

Runtime Error: bad argument #1 to 'math.randomseed' (integer expected, got nil)
stack traceback:
	[C]: in function 'math.randomseed'
	C:\Program Files (x86)\Steam\steamapps\workshop\content\289070\871861883\Override\AdvancedSetup.lua:206: in function 'GetShuffledCopyOfTable'
	C:\Program Files (x86)\Steam\steamapps\workshop\content\289070\871861883\Override\AdvancedSetup.lua:1398: in function 'OnStartButton'
	[C]: in function '(anonymous)'
Lua callstack:

[Lua.log](https://github.com/Gedemon/Civ6-YnAMP/files/4512344/Lua.log)
![20200421220115_1](https://user-images.githubusercontent.com/61685124/79908702-fbb2bd80-841b-11ea-8b60-292c30cdcf4b.jpg)

**Comment by Gedemon** [comment]
Thanks, I'll have a look, should be easy to fix for solo (used to seed the Lua random function), but will need a solution for MP when I'll try to make the new options available in that mode.

**Comment by Gedemon** [comment]
should be fixed now
