### ISSUE TITLE
forest fire bonus cumulative

### ISSUE THREAD

**Issue by ozorfis** [Gedemon/Civ6-YnAMP#140]
I´m playing giant earth map with the latest june update. The bonuses from forest fires seem to be cumulative so that after a couple of fires all tiles yield 10 food and production. Is this intended? To me it seems buggy is it is way overpowered.

**Comment by 1e00** [comment]
I think new update will fix that problem: https://youtu.be/ezIZD0gKIyk?t=150

**Comment by ozorfis** [comment]
Thank you very much for that information.
