### ISSUE TITLE
Americas on the west side

### ISSUE THREAD

**Issue by SpikerzZ406** [Gedemon/Civ6-YnAMP#145]
Is there a way to have the giant map with the earth normal to Canada where we are on the West and Europe is on the East side of the world?

**Comment by Gedemon** [comment]
You should be able to do that with the version uploaded today:

When using a custom section of a map (Giant Earth Map / Largest Earth Map), selecting the same latitude for east/west borders will now generate the map using that latitude for the left side of the minimap. It should allow you to generate a Giant Earth Map with the Americas on the left side using the "Bering Strait" latitude for both east/west borders.

**Comment by SpikerzZ406** [comment]
that's awesome, is the giant map working now? Or does it still crash when sea levels rise and in late game?

**Comment by SpikerzZ406** [comment]
One more question, I can't find the download for today, steam says November, not sure where the github one is and the civfrantic is 2018

**Comment by Gedemon** [comment]
go here:
https://github.com/Gedemon/Civ6-YnAMP
click "code" then download zip

full instruction here, do not use both steam and github versions at the same time.
https://forums.civfanatics.com/threads/installation-instructions.655901/

the update here was exceptional, use SeelingCat github if you prefer it over steam, he accepted to manage the mod and update it for the game's new patches. (civfanatics link should point you to his gitHub)

I've stopped modding/playing, but I know Firaxis has still not be able to fix the late game issues on larger maps.

**Comment by SpikerzZ406** [comment]
Thanks it works, I have 64GB Ram good CPU awesome GPU we need a way to play this map to the end lol
