### ISSUE TITLE
Accepting delegations from certain leaders locks the map at the edge of the screen

### ISSUE THREAD

**Issue by 0SirLoin** [Gedemon/Civ6-YnAMP#16]
When you accept delegations from Scythia or Sumeria (who are on the edge of the map) and the focus goes to their capital city sometimes the map locks there and you can't scroll away. This even persists after saving/loading making the game unplayable. You can't get rid of that screen, you are totally stuck with half scrolled outside of the map.

**Comment by Gedemon** [comment]
Is this still hapenning ?

It may have been fixed on Firaxis side.
