### ISSUE TITLE
Walkable Bosphorus

### ISSUE THREAD

**Issue by XtroTheArctic** [Gedemon/Civ6-YnAMP#2]
Please add an option to make Istanbul Bosphorus walkable with only one tile so a city built on this tile can connect Black sea to Aegean. A river would be nice as Bosphorus.

I edited the necessary line for you:
 MapToConvert[32][60]={0,2,-1,4,{{0,-1},{0,-1},{1,4}},{-1,0}}

**Comment by Gedemon** [comment]
option added https://github.com/Gedemon/Civ6-YnAMP/commit/dc831ce3eefa1519e211420f878d4f5246c6ca82
