### ISSUE TITLE
Using Europe map some civs replace each other

### ISSUE THREAD

**Issue by Sergey-Reg** [Gedemon/Civ6-YnAMP#24]
True start locations option is turned on.
I play for Scythia. Fist city(Pokrovka) of Scythia may appear on British Island and then be changed to London. Or some AI players may replace one another, e.g. Greece or Italy can have a Moscow city.

**Comment by Gedemon** [comment]
Potential bug on the Mac version with settings requirement not being applied correctly and the "Cultural Location" option being shown and initialized as a consequence.

**Comment by ajouellette** [comment]
I've noticed this same issue (on Windows). For me, it's always Rome and Russia being switched.

**Comment by Gedemon** [comment]
I can't reproduce that, I'd like the lua.log (on windows) after starting a game showing this problem

**Comment by ajouellette** [comment]
Hm, it looks like the problems might have been fixed. I can't seem to reproduce it either.
