### ISSUE TITLE
Largest Earth Map causes memory leak when loading leader's textures

### ISSUE THREAD

**Issue by ianyanian** [Gedemon/Civ6-YnAMP#27]
I found an interesting memory leak bug. Most likely this is a game engine issue but I just want to share it here

After finished loading the map, used the reveal all command and clicked on a leader:
http://i.imgur.com/xcYSAD0.jpg

Press any leader, go back, press any leader again, go back, repeat until run out of VRAM:
http://i.imgur.com/1YSxR5T.jpg

**Comment by Gedemon** [comment]
not something I can fix I'm afraid.
