### ISSUE TITLE
Game crashes on Inland Sea map generation

### ISSUE THREAD

**Issue by TehSeph** [Gedemon/Civ6-YnAMP#3]
When using one of the added map sizes with the Inland Sea generation, my game is crashing during the initial loading screen. This only happens with Inland Sea and the other generators are working fine (at least the ones I've played; Continents, Islands, & Pangaea.)

I'm using v0.7 from the [CivFanatics website](http://forums.civfanatics.com/resources/ynamp-yet-not-another-maps-pack-for-civ6.25395/).

**Comment by MarishKaczmarek** [comment]
I noticed that the Inland Sea map seems to conflict with a lot of mods, I noticed crashes when making any in-game changes with CQUI.

**Comment by Gedemon** [comment]
I think this map use its own size table linked to the default map sizes, so I've limited the sizes option to the vanilla options when selecting this map.
