### ISSUE TITLE
CQUI Incompatibility

### ISSUE THREAD

**Issue by chaorace** [Gedemon/Civ6-YnAMP#43]
I've gotten multiple reports that this mod breaks the core logic in CQUI, which is pretty strange considering how tangential a map mod and a UI mod are in what they change! I actually can't seem to find any file overlap at all, yet it's definitely breaking CQUI when used in tandem with it. Anyways, I just thought I'd remark upon that in case you maybe had any leads. Here's [the companion issue](https://github.com/chaorace/cqui/issues/207) over on the CQUI tracker

**Comment by Gedemon** [comment]
I can't reproduce the issue mentioned on CQUI tracker, but I do have noted a lag when opening the city tab (~1 seconde at giant size, ~4-5 at "ludicrous" size) using both mod together, could this be related to map size ?

do you have links to other reports ?

**Comment by SpaceOgre** [comment]
@Gedemon Just to let you know that we have fixed the problem on the CQUI end (hopefully anyway).
