### ISSUE TITLE
How To Add Cities

### ISSUE THREAD

**Issue by wevertonj** [Gedemon/Civ6-YnAMP#54]
Hi,

I'd like add Latin America cities names to Aztecs and Brazil, but I don't find the documentation. I took a look at the code and seems easy to add, I only don't understand what are x and y attributes.

**Comment by Gedemon** [comment]
For x, y see "Get map coords and reveal the whole map" in the second post of this thread:
https://forums.civfanatics.com/threads/ynamp-sub-project-true-location-corresponding-city-names.605960/
