### ISSUE TITLE
Khmer TSL and suks tonle sap

### ISSUE THREAD

**Issue by Frunobulaxian** [Gedemon/Civ6-YnAMP#82]
from lua.log:
Map Script: - CIVILIZATION_KHMER at 77,40
Map Script: WARNING ! Plot is out of land !

Replace MapName="GiantEarth" Civilization="CIVILIZATION_KHMER"		X="77" Y="40" />

(MapName, 		FeatureType,						X, 	Y)
VALUES	('GiantEarth', 	'FEATURE_SUK_TONLESAP',				76, 41),
		('GiantEarth', 	'FEATURE_SUK_TONLESAP',				77, 40),

i rolled him back to his old plot and the crashing to desktop stopped.
Replace MapName="GiantEarth" Civilization="CIVILIZATION_KHMER"		X="76" Y="42" />

**Comment by Gedemon** [comment]
thanks, should have been fixed now.

**Comment by Frunobulaxian** [comment]
Thank you for taking the time to work on this.
