### ISSUE TITLE
game continues to crash post Rn F

### ISSUE THREAD

**Issue by ghengiseanie** [Gedemon/Civ6-YnAMP#84]
Hi all, I have downlaoded hte updated master.. But for some reason I cannot get any game ot start with this mod enabled. EVen if i do not choose a YNAMP map..

**Comment by pranafox** [comment]
Hi!
Sadly, there must be something in RnF that changed parts of map generation or map loading, and it makes its rule-set incompatible with YnAMP. This conclusion comes after having the same issue as you, and then wondering to myself if it has anything to do with the new expansion's rule-set.
The solution? Change the rule-set in "create game" from "Rise and Fall" to "Standard." Should work fine!

**Comment by Gedemon** [comment]
define "continue to crash" please.

latest version is compatible with R&F, but you may need a fix if you use DLC, see https://forums.civfanatics.com/resources/workaround-when-returning-to-main-menu-with-r-f-and-some-mods.26701/

if the base maps are not listed, you don't have the latest commit.

**Comment by ghengiseanie** [comment]
Sorry its the return to main menu bug i think, It works with the Terra Expanded Map, but not the Ynamps maps, and it is the RnF ruleset..

**Comment by Gedemon** [comment]
If the fix isn't working for you, you'll have to wait for Firaxis patch.

**Comment by ghengiseanie** [comment]
all good now thanks :) May i query if the cliffs of dover tweaks and etc in add ons, are no longer compatible?

**Comment by ghengiseanie** [comment]
and fantastic work much aprpeciated by the way

**Comment by ghengiseanie** [comment]
ANy chance of a decent Indonesia map? (i moved here a while back and couldn't explore all the islands in a life time..
