### ISSUE TITLE
Installs fine in non-steam Mac version, but doesn't seem usable

### ISSUE THREAD

**Issue by tog22** [Gedemon/Civ6-YnAMP#85]
I've followed the instructions on https://github.com/Gedemon/Civ6-YnAMP for installing Yet (not) Another Maps Pack for the non-Steam Mac version. I've checked 'enable' next to it under the 'Additional Content' menu option, but after doing so (and restarting the game) I can't see any option to use it. When I choose advanced setup under single player as instructed all I see is http://prntscr.com/im8e6q

What do I do? Help!

**Comment by Gedemon** [comment]
First update the game to the latest version (you're using a very old one), then use beta 6.2 if you're using a mac:
https://forums.civfanatics.com/resources/ynamp-yet-not-another-maps-pack-for-civ6.25395/history
