### ISSUE TITLE
Game runs without me

### ISSUE THREAD

**Issue by E-Reg** [Gedemon/Civ6-YnAMP#92]
Hello,

I am on 1.0.0.167 and with Beta 6.3 every game with your mod enabled simply starts without me - map not being revealed, Years go by :-)
Do I need to take an older version of the mod for this certain version of the game (which? Oct 11?)
I tried turning the sea script on and off as well as the cultural starting position.

Greetings,

E-Reg

**Comment by Gedemon** [comment]
New patches may break compatibility, you need to find the last version of the mod before the patch following your version of the game.
